version: "3.9"

services:
  app:
    build:
      context: .
    restart: always
    ports:
      - "3000:3000"
    command:
      - /bin/sh
      - -c
      - |
        go build -ldflags="-s -w" ./cmd/app/main.go &&
        ./main
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: boilerplate
      POSTGRES_PASSWORD: secret
    ports:
      - "5454:5432"
    volumes:
      - ./data:/var/lib/postgres
